name: releaser
on:
  push:
    tags: ['*']
jobs:
  create-release:
    name: Release pushed tag
    runs-on: ubuntu-24.04
    steps:
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
      run: gh release create "$tag" --repo="$GITHUB_REPOSITORY" --title="${tag#v}" --generate-notes
